# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuildTest

on:
  push:
    branches: [ "master","actions" ]
  pull_request:
    branches: [ "master","actions" ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run workflow on'
        required: true
        default: 'main'

permissions:
  contents: read

jobs:
  setup-boost:
    runs-on: windows-2019
    steps:
    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v1.3.3
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: boost
        path: boost.zip
      continue-on-error: true
    - name: Check artifact
      run: |
        if (Test-Path -Path ./boost) {
          echo "artifact-exists=true" >> $env::GITHUB_ENV
        } else {
          echo "artifact-exists=false" >> $env::GITHUB_ENV
        }
    - name: Download Boost
      if: ${{ env.artifact-exists != 'true' }}
      shell: cmd
      run: |
        git clone -b boost-1.85.0 --depth 1 --recursive https://github.com/boostorg/boost.git boost
        msbuild -version
    - name: Setup Boost 1
      if: ${{ env.artifact-exists != 'true' }}
      shell: cmd
      run: |
        cd boost
        echo "=== bootstrap.bat ==="
        bootstrap.bat
    - name: Setup Boost 2
      if: ${{ env.artifact-exists != 'true' }}
      shell: cmd
      run: |
        cd boost
        echo "=== b2 headers ==="
        b2 headers
    - name: Compress
      if: ${{ env.artifact-exists != 'true' }}
      shell: powershell
      run: |
        Compress-Archive -Path boost\boost\ -DestinationPath .\boost.zip
    - name: Check zip
      if: ${{ env.artifact-exists != 'true' }}
      shell: cmd
      run: dir
    - name: Upload artifact
      if: ${{ env.artifact-exists != 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: boost
        path: boost.zip

  build:
    runs-on: windows-latest
    needs: setup-boost
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v1.3.3
    - name: Download boost
      uses: actions/download-artifact@v4
      with:
        name: boost
        path: boost
    - name: Expand
      shell: powershell
      run: |
        Expand-Archive -Path boost\boost.zip -DestinationPath boost\
    - name: Set BOOST_ROOT
      shell: powershell
      run: echo "BOOST_ROOT=boost" >> $env:GITHUB_ENV
    - name: Build
      shell: cmd
      id: build
      run: |
        msbuild /p:Platform="x86" /p:Configuration=Release ./src/KbAsciiMml.sln
        msbuild /p:Platform="x64" /p:Configuration=Release ./src/KbAsciiMml.sln
        echo "::set-output name=sha7::$(git rev-parse --short HEAD)"
      env:
        BOOST_ROOT: ${{ env.BOOST_ROOT }}
    - name: Package
      run: |
        mkdir -p artifact/x86 artifact/x64
        cp bin/KbAsciiMml/Win32/Release/KbAsciiMml.dll artifact/x86/KbAsciiMml/kpi
        cp bin/KbAsciiMml/x64/Release/KbAsciiMml.dll artifact/x64/KbAsciiMml/kpi
        cp KbAsciiMml.ini artifact/x86/KbAsciiMml.ini
        cp KbAsciiMml.ini artifact/x64/KbAsciiMml.ini
        cp KpAsciiMml_e.txt artifact/x86/KpAsciiMml_e.txt
        cp KpAsciiMml_e.txt artifact/x64/KpAsciiMml_e.txt
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: KpAsciiMml_e-${{ steps.build.outputs.sha7 }}
        path: artifact
