# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuildTest

on:
  push:
    branches: [ "master","actions" ]
  pull_request:
    branches: [ "master","actions" ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run workflow on'
        required: true
        default: 'main'

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.3.3
      with:
        vs-version: '[17.0,17.8)'

    - name: Cache Boost
      uses: actions/cache@v4
      id: cache_boost
      with:
        path: "boost"
        key: boost-1.85.0-${{ runner.os }}
  
    - name: Download Boost
      if: ${{ steps.cache_boost.outputs.cache-hit != 'true' }}
      shell: cmd
      run: |
        git clone -b boost-1.85.0 --depth 1 --recursive https://github.com/boostorg/boost.git boost
        cd boost
        echo "=== bootstrap.bat ==="
        bootstrap.bat
        dir

    - name: Install Boost 2
      shell: cmd
      run: |
        cd boost
        echo "=== b2 headers ==="
        b2 headers

    - name: Set env
      shell: powershell
      run: |
        echo "=== set env ==="
        echo "BOOST_ROOT=${{ github.workspace }}\boost" >> $env:GITHUB_ENV

    - name: Build
      shell: cmd
      run: |
        msbuild /m /p:Platform="x86" /p:Configuration=Release "src\KbAsciiMml.sln"
        msbuild /m /p:Platform="x64" /p:Configuration=Release "src\KbAsciiMml.sln"
      env:
        BOOST_ROOT: ${{ env.BOOST_ROOT }}

    - name: Package
      run: |
        mkdir -p artifact/x86 artifact/x64
        cp bin/KbAsciiMml/Win32/Release/KbAsciiMml.dll artifact/x86/KbAsciiMml/kpi
        cp bin/KbAsciiMml/x64/Release/KbAsciiMml.dll artifact/x64/KbAsciiMml/kpi
        cp KbAsciiMml.ini artifact/x86/KbAsciiMml.ini
        cp KbAsciiMml.ini artifact/x64/KbAsciiMml.ini
        cp KpAsciiMml_e.txt artifact/x86/KpAsciiMml_e.txt
        cp KpAsciiMml_e.txt artifact/x64/KpAsciiMml_e.txt

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: KpAsciiMml_e
        path: artifact
