# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuildTest

on:
  push:
    branches: [ "master","actions" ]
  pull_request:
    branches: [ "master","actions" ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run workflow on'
        required: true
        default: 'main'

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install MSBuild
      run: |
        choco install visualstudio2022buildtools --version 117.9.7.0
        choco install visualstudio2022-workload-vctools

    - name: Cache Boost
      uses: actions/cache@v4
      id: cache_boost
      with:
        path: "boost"
        key: boost-1.85.0-${{ runner.os }}
  
    - name: Download Boost
      if: ${{ steps.cache_boost.outputs.cache-hit != 'true' }}
      shell: cmd
      run: |
        git clone -b boost-1.85.0 --depth 1 --recursive https://github.com/boostorg/boost.git boost

    - name: Install Boost 1
      shell: cmd
      run: |
        msbuild -version
        cd boost
        echo "=== bootstrap.bat ==="
        bootstrap.bat
        dir

    - name: Install Boost 2
      shell: cmd
      run: |
        cd boost
        echo "=== b2 headers ==="
        b2 headers
        dir
